### PR TITLE
fix(metricsrouter): update platform-services-go-sdk to add ca-mon sup…

### PR DESCRIPTION
**Pull request by wenjian2**
…port

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TEST=./ibm/service/metricsrouter TESTARGS='-run=TestAccIBMMetricsRouterSettingsBasic'
...
=== RUN   TestAccIBMMetricsRouterRoutesDataSourceBasic
--- PASS: TestAccIBMMetricsRouterRoutesDataSourceBasic (17.99s)
=== RUN   TestAccIBMMetricsRouterTargetsDataSourceBasic
--- PASS: TestAccIBMMetricsRouterTargetsDataSourceBasic (11.80s)
=== RUN   TestAccIBMMetricsRouterTargetsDataSourceAllArgs
--- PASS: TestAccIBMMetricsRouterTargetsDataSourceAllArgs (14.67s)
=== RUN   TestAccIBMMetricsRouterRouteBasic
--- PASS: TestAccIBMMetricsRouterRouteBasic (22.03s)
=== RUN   TestAccIBMMetricsRouterRouteConfigBasicWithoutAction
--- PASS: TestAccIBMMetricsRouterRouteConfigBasicWithoutAction (10.74s)
=== RUN   TestAccIBMMetricsRouterRouteSendEmptyTarget
--- PASS: TestAccIBMMetricsRouterRouteSendEmptyTarget (0.46s)
=== RUN   TestAccIBMMetricsRouterRouteDropEmptyTarget
--- PASS: TestAccIBMMetricsRouterRouteDropEmptyTarget (0.45s)
=== RUN   TestAccIBMMetricsRouterRouteDropNoTarget
--- PASS: TestAccIBMMetricsRouterRouteDropNoTarget (11.07s)
=== RUN   TestAccIBMMetricsRouterRouteSendNoTarget
--- PASS: TestAccIBMMetricsRouterRouteSendNoTarget (4.38s)
=== RUN   TestAccIBMMetricsRouterSettingsBasic
--- PASS: TestAccIBMMetricsRouterSettingsBasic (12.68s)
=== RUN   TestAccIBMMetricsRouterSettingsAllArgs
--- PASS: TestAccIBMMetricsRouterSettingsAllArgs (12.79s)
=== RUN   TestAccIBMMetricsRouterSettingsEmptyTarget
--- PASS: TestAccIBMMetricsRouterSettingsEmptyTarget (0.46s)
=== RUN   TestAccIBMMetricsRouterTargetBasic
--- PASS: TestAccIBMMetricsRouterTargetBasic (21.41s)
=== RUN   TestAccIBMMetricsRouterTargetAllArgs
--- PASS: TestAccIBMMetricsRouterTargetAllArgs (19.49s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/metricsrouter   161.911s
...
```

### CODE REVIEW

**Comment by yingwang-us** [comment]
Atracker tests:
Screenshot 2025-07-16 at 2 15 39 PM

File: go.mod [hunk 1]
```diff
@@ -28,7 +28,7 @@ require (
 	github.com/IBM/logs-router-go-sdk v1.0.8
 	github.com/IBM/mqcloud-go-sdk v0.2.0
 	github.com/IBM/networking-go-sdk v0.51.9
-	github.com/IBM/platform-services-go-sdk v0.83.3
+	github.com/IBM/platform-services-go-sdk v0.84.2
```
Comment (hkantare) [inline go.mod]: Can we upgrade to latest paltform SDK the older release has issue with global catalog
https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.84.4

More details on slack https://ibm-cloudplatform.slack.com/archives/C8147V4PK/p1752127727912899

Comment (wenjian2) [reply go.mod]: @hkantare After upgrading to v0.84.4, I got the following build error. Is there another PR updating iampolicy?
```
# github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/iampolicy
ibm/service/iampolicy/data_source_ibm_iam_action_control_assignment.go:400:93: undefined: iampolicymanagementv1.ErrorResponse
ibm/service/iampolicy/data_source_ibm_iam_action_control_assignments.go:428:95: undefined: iampolicymanagementv1.ErrorResponse
ibm/service/iampolicy/data_source_ibm_iam_policy_assignment.go:356:81: undefined: iampolicymanagementv1.ErrorResponse
ibm/service/iampolicy/data_source_ibm_iam_policy_assignments.go:477:83: undefined: iampolicymanagementv1.ErrorResponse
ibm/service/iampolicy/resource_ibm_iam_action_control_assignment.go:566:88: undefined: iampolicymanagementv1.ErrorResponse
```

Comment (yingwang-us) [reply go.mod]: same, with [v0.84.4](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.84.4) I get the same compile erros.

Comment (uibm) [reply go.mod:31]: Can you try updating those with `AssignmentResourceError`

ErrorResponse at those lines with AssignmentResourceError

Comment (wenjian2) [reply go.mod]: v0.84.4 is already in master by another PR.
